#!/usr/bin/env python3
"""Build one misc/ cell headlessly: GDS plus a KLayout render of that GDS.

    make gf-inverter        # scripts/run-gf-inverter.sh:   python3 misc/build.py
    make gf-comparator      # scripts/run-gf-comparator.sh: python3 misc/build.py CMP_LP
                            #   then python3 misc/build.py --control CMP_LP

Runs inside the pinned IIC-OSIC-TOOLS container with the gf180mcu plugin
from .eda-tools/ (`make tools`). Writes, GDSFactory+ style, under build/:

    build/gds/<CELL>.gds
    build/render/<CELL>.png
    build/<CELL>.spice      (CMP_LP only) the LVS reference, generated
    build/control/<CELL>.gds  (--control) the same GDS with inp/inn swapped

Every figure of merit is one `name = value` line on stdout, which the
cell's check-*.awk turns into PASS/FAIL and scripts/sim.sh folds into
metrics.json. DRC and LVS are ../signoff.py's, run by the shell script.
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BLOCK = os.path.dirname(HERE)
OUT = os.path.join(HERE, "build")
CMP_SOURCE = os.path.join(BLOCK, "..", "comparator_lp", "cmp_lp.spice")

sys.path.insert(0, HERE)

import gdsfactory as gf  # noqa: E402
import gf180mcu  # noqa: E402

from gfp_misc.cells.comparator import CMP_LP, DEVICES  # noqa: E402
from gfp_misc.cells.inverter import INV_GF  # noqa: E402

#- ports the layout draws, in cmp_lp.spice's order; clk and nbias are ports
#- of the subcircuit that no device connects to
CMP_PINS = ("inp", "inn", "dout", "vdd", "vss", "pbias")

# cell name -> (factory, transistor count, pin names)
CELLS = {"INV_GF": (INV_GF, 2, ("A", "Y", "VDD", "VSS")),
         "CMP_LP": (CMP_LP, len(DEVICES), CMP_PINS)}


def render(cell, gds, png):
    env = dict(os.environ, QT_QPA_PLATFORM="offscreen")
    r = subprocess.run(["klayout", "-z", "-rd", "input=" + gds, "-rd", "out=" + png,
                        "-r", os.path.join(BLOCK, "klayout", "render.rb")],
                       cwd=HERE, env=env, text=True,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    with open(os.path.join(OUT, f"render-{cell}.log"), "w") as fo:
        fo.write(r.stdout)
    return os.path.getsize(png) if os.path.exists(png) else 0


def cmp_reference(path):
    """The LVS reference for CMP_LP, generated from cmp_lp.spice.

    The transistor lines are copied verbatim. What changes, and why:
    COUTA is dropped -- it is the recipe's stand-in for layout parasitics,
    which extraction of this layout now supplies; the subcircuit is named
    after the layout cell and carries the six ports the layout draws.
    Returns (transistor count, dropped element names)."""
    body, dropped, ports = [], [], None
    inside = False
    for line in open(CMP_SOURCE):
        s = line.strip()
        if s.lower().startswith(".subckt cmp"):
            inside = True
            ports = s.split()[2:]
            continue
        if not inside:
            continue
        if s.lower().startswith(".ends"):
            break
        if not s or s.startswith("*"):
            continue
        if s[0] in "Xx" and re.search(r"\b[np]fet_03v3\b", s):
            body.append(s)
        else:
            dropped.append(s.split()[0])
    missing = [p for p in CMP_PINS if p not in (ports or [])]
    if missing:
        raise SystemExit(f"cmp_lp.spice has no port(s) {missing}")
    with open(path, "w") as fo:
        fo.write("* LVS reference for misc/gfp_misc/cells/comparator.py (CMP_LP).\n"
                 "* GENERATED by misc/build.py from comparator_lp/cmp_lp.spice -- do not edit.\n"
                 f"* Dropped: {' '.join(dropped) or 'nothing'} (routing-load stand-in; "
                 "extraction supplies it).\n"
                 f"* Ports not drawn: {' '.join(p for p in ports if p not in CMP_PINS)} "
                 "(no device connects to them).\n"
                 f".subckt CMP_LP {' '.join(CMP_PINS)}\n")
        for s in body:
            fo.write(s + "\n")
        fo.write(".ends CMP_LP\n")
    return len(body), dropped


def swapped_pins_control(gds, out, a="inp", b="inn"):
    """A copy of `gds` with the texts of pins `a` and `b` exchanged.

    Nothing about the geometry changes, so it is exactly as DRC clean as
    the real cell; LVS has to call it a mismatch, or a match on the real
    cell says nothing about the pins. inp and inn are not interchangeable
    in the circuit (inp drives the side whose drain is the diode node), so
    a comparison that reads the pin names must tell them apart."""
    import klayout.db as kdb
    layout = kdb.Layout()
    layout.read(gds)
    top = layout.top_cell()
    swapped = 0
    for li in layout.layer_indexes():
        for sh in top.shapes(li).each():
            if sh.is_text() and sh.text_string in (a, b):
                t = sh.text
                t.string = b if sh.text_string == a else a
                sh.text = t
                swapped += 1
    os.makedirs(os.path.dirname(out), exist_ok=True)
    layout.write(out)
    return swapped


def main():
    if sys.argv[1:2] == ["--control"]:
        cell = sys.argv[2]
        gds = os.path.join(OUT, "gds", cell + ".gds")
        out = os.path.join(OUT, "control", cell + ".gds")
        print(f"{cell.lower()}_ctl_swapped_labels = {swapped_pins_control(gds, out)}")
        return
    cell = sys.argv[1] if len(sys.argv) > 1 else "INV_GF"
    if cell not in CELLS:
        raise SystemExit(f"unknown cell {cell}; one of {', '.join(CELLS)}")
    factory, want, pins = CELLS[cell]
    gf180mcu.PDK.activate()
    for d in ("gds", "render"):
        os.makedirs(os.path.join(OUT, d), exist_ok=True)

    c = factory()
    if c.name != cell:
        raise SystemExit(f"cell is named {c.name}, signoff expects {cell}")
    gds = os.path.join(OUT, "gds", cell + ".gds")
    c.write_gds(gds)

    devices = sum(1 for inst in c.insts if inst.cell.name.startswith(("nfet", "pfet")))
    labels = sorted(_labels(c))
    low = cell.lower()
    print(f"# gdsfactory {gf.__version__}, gf180mcu {gf180mcu.__version__}")
    print(f"{low}_devices = {devices}")
    print(f"{low}_devices_expected = {want}")
    #- a pin is a label named after a port; any other label names an
    #- internal net for the extracted netlist
    print(f"{low}_pins = {sum(1 for p in pins if p in labels)}")
    print(f"{low}_pins_expected = {len(pins)}")
    print(f"{low}_pin_names = {','.join(p for p in pins if p in labels)}")
    print(f"{low}_net_labels = {','.join(n for n in labels if n not in pins) or 'none'}")
    print(f"{low}_width_um = {c.dxsize:.3f}")
    print(f"{low}_height_um = {c.dysize:.3f}")
    print(f"{low}_area_um2 = {c.dxsize * c.dysize:.1f}")
    print(f"{low}_gds_bytes = {os.path.getsize(gds)}")
    print(f"{low}_render_bytes = "
          f"{render(cell, gds, os.path.join(OUT, 'render', cell + '.png'))}")
    if cell == "CMP_LP":
        n, dropped = cmp_reference(os.path.join(OUT, cell + ".spice"))
        print(f"{low}_ref_devices = {n}")
        print(f"{low}_ref_dropped = {','.join(dropped) or 'none'}")


def _labels(c):
    """Text labels on the cell's own shapes (the pins)."""
    layout = c.kcl.layout
    for li in layout.layer_indexes():
        for sh in c.kdb_cell.shapes(li).each():
            if sh.is_text():
                yield sh.text_string


if __name__ == "__main__":
    main()
